# Generated by Django 3.0.8 on 2020-07-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jk', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(upload_to='media'),
            preserve_default=False,
        ),
    ]
