# Generated by Django 3.0.8 on 2020-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jk', '0003_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_offer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(),
        ),
    ]
